DotnetIdentity: DotNetIdentity.IdentitySettings.ErrorDescriber Class Reference
DotNetIdentity.IdentitySettings.ErrorDescriber Class Reference
class to override IdentityErrorDescriber IdentotyError messages
Static Public Member Functions
static IdentityError PasswordContainsUsername ()
custom IdentityError if password contains username
static IdentityError UserNameLength ()
custom IdentityError if username length is too short
static IdentityError UserNameContainsEmail ()
custom IdentityError if username contains user email
Detailed Description
class to override IdentityErrorDescriber IdentotyError messages
Definition at line 8 of file ErrorDescriber.cs.
Member Function Documentation
PasswordContainsUsername()
static IdentityError DotNetIdentity.IdentitySettings.ErrorDescriber.PasswordContainsUsername () static
custom IdentityError if password contains username
Returns
IdentityError
Referenced by DotNetIdentity.IdentitySettings.Validators.PasswordValidator.ValidateAsync().
UserNameContainsEmail()
static IdentityError DotNetIdentity.IdentitySettings.ErrorDescriber.UserNameContainsEmail () static
custom IdentityError if username contains user email
Returns
IdentityError
Referenced by DotNetIdentity.IdentitySettings.Validators.UserValidator.ValidateAsync().
UserNameLength()
static IdentityError DotNetIdentity.IdentitySettings.ErrorDescriber.UserNameLength () static
custom IdentityError if username length is too short
Returns
IdentityError
Referenced by DotNetIdentity.IdentitySettings.Validators.UserValidator.ValidateAsync().
The documentation for this class was generated from the following file:
/Users/sascha.heimann/Projects/dotnet-cookie-based-identity/DotNetIdentity/IdentitySettings/ErrorDescriber.cs